<?xml version="1.0" encoding="utf-8"?><Database Name="tmppasindu" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.44.107.12;Initial Catalog=tmppasindu;User ID=sa" SettingsObjectName="StockManagemengBasic.Properties.Settings" SettingsPropertyName="tmppasinduConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblStock" Member="tblStocks">
    <Type Name="tblStock">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SellPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="PurchasePrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AlertQty" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>